### Tutorial Section


In [7]:
import numpy as np
import torch

#### Tensor initialisation

In [8]:
data = [[5,9],[3,7]]
x_data = torch.tensor(data) 
# creating a "tensor" out of data, similar to an ndarray, data type inferred automatically

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
# creating a tensor from a numpy array

x_data
x_np
# Both should return the same output

tensor([[5, 9],
        [3, 7]])

#### making a tensor from an existing one

In [9]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=float)

x_ones # should return the same tensor dimension as before with 1s


tensor([[1, 1],
        [1, 1]])

In [10]:
x_rand # should return random float values in the same dimension as x_data

tensor([[0.6086, 0.9298],
        [0.7547, 0.6230]], dtype=torch.float64)

#### We can also create tensors of certain shape using zeroes, ones or random numbers

In [11]:
shape = [3, 2]
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0162, 0.1877],
        [0.2938, 0.2580],
        [0.7001, 0.7589]]) 

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [12]:
rand_tensor.device

device(type='cpu')

In [13]:
rand_tensor.shape

torch.Size([3, 2])

In [14]:
rand_tensor.dtype

torch.float32

In [15]:
rand_tensor[:,1]=0
rand_tensor

tensor([[0.0162, 0.0000],
        [0.2938, 0.0000],
        [0.7001, 0.0000]])

In [21]:
t1 = torch.cat ([rand_tensor,ones_tensor, zeros_tensor], dim=-2)
t1

tensor([[0.0162, 0.0000],
        [0.2938, 0.0000],
        [0.7001, 0.0000],
        [1.0000, 1.0000],
        [1.0000, 1.0000],
        [1.0000, 1.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000]])